### ISSUE TITLE
Thoughts on environment propagation

### ISSUE THREAD

**Issue by paxperscientiam** [midwire/bash.env#8]
Hey, I'm wondering why `propagate_env_to_host()` [excludes] the (https://github.com/midwire/bash.env/blob/4b3f222158736c065f857bcf5fe079c62542e952/global/global_functions.sh#L118ef) ".git" directory. 

To me, this actually hampers the utility of bash.env: if I make changes to my environment on remote Host A, I'd like to be able to push those changes to the git remote (in this scenario, I've forked this repo).

As .git is excluded in the propagation process, I'm locked into having to make edits locally and then propagating again to, in this case, Host A.

Was this just a design choice, or is just a temporary fix for a harder problem?

**Comment by midwire** [comment]
> if I make changes to my environment on remote Host A, I'd like to be able to push those changes to the git remote (in this scenario, I've forked this repo).

Greetings.  I'm a bit confused by the description of the problem.  It seems you have a remote `Host A` where you make changes to bash.env.  Then you want to propagate those changes to another host, or to your forked git repo?

In answer to your question, I leave out the `.git` directory (et. al.) four a few reasons:

1. it/they can become quite large (although it is ~2k right now), and sometimes remote hosts are space limited.
2. those files/directories serve no functional purpose, from a bash.env perspective
3. my bash.env workflow is such that if I make changes, I tend to always push them from my local machine to the remotes

I do, however, see that it may be useful to manage bash.env hosts through Git.  In other words, propagate the `.git` directory to the remote hosts, allowing any remote host changes to be committed to the repository, then pulled back down to the appropriate hosts (or local).

Let me think about this.  It may be worth making that behavior the default and adding a switch to exclude the `.git` directory.  And if I have an incorrect understanding about what you are trying to accomplish please let me know.

**Comment by midwire** [comment]
@paxperscientiam After thinking about this, I don't see a down side to including the `.git` directory and if it helps with your (and maybe others') workflows it is worth doing.  See PR: https://github.com/midwire/bash.env/pull/9

**Comment by paxperscientiam** [comment]
Yeah, it was pretty late when I created this issue: I could have been clearer! 

That said, thanks for the change. If it for some reason this becomes problematic, there's always the alternative to make inclusion of the .git directory optional re propagation.
